[variables]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
INLINE_RUNTIME_CHUNK = "false"

[build]
cmd = "npm install && npm run build"

[start]
cmd = "npx serve -s build -l 3000"

[phases.setup]
nixPkgs = ["nodejs_18"]
